---
- name: Install requirements (apt)
  become: true
  apt:
    name: 
      - neovim
      - python3-pip
      - nodejs
      - clangd
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Install requirements (pacman)
  become: true
  pacman:
    name:
      - neovim
      - python-pip
      - nodejs
      - clang
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "ArchLinux"

- name: Install requirements (dnf)
  become: true
  dnf:
    name:
      - neovim
      - python3-pip
      - nodejs
      - clang
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "RedHat"

- name: Install requirements (homebrew)
  homebrew:
    name: 
      - neovim
      - node
    state: present
  when: ansible_facts['os_family'] == "Darwin"

- name: Install clang on macos
  shell: xcode-select --install
  when: ansible_facts['os_family'] == "Darwin"


